#!/bin/bash

$ROOT/install -p dotbot-yay/yay.py -p dotbot-vscode/vscode.py -c applications.conf.yaml

# Spotifyd
sudo systemctl enable spotifyd --machine=$USER@.host --user --now

# Syncthing
sudo systemctl enable --now syncthing@$USER

# Docker
sudo usermod -aG docker $USER

# Neovim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

cd ~/.local/share/nvim/plugged/YouCompleteMe && python3 install.py --all 
