#!/bin/bash

# NetworkManager
sudo systemctl enable NetworkManager --now

# Flutter
sudo gpasswd -a $USER flutterusers

# sddm
sudo systemctl enable ly

# Micro
micro -plugin install quoter filemanager

# ZSH
$ROOT/scripts/install-zsh

$ROOT/scripts/chaotic-aur

# Update user
$ROOT/scripts/chuser

# Set locale
$ROOT/scripts/set-locale
