#!/bin/bash

# NetworkManager
sudo systemctl enable NetworkManager --now

# Flutter
sudo gpasswd -a $USER flutterusers

# sddm
sudo systemctl enable sddm
sudo cp $DOTFILES/themes/zune /usr/share/sddm/themes/ -r

# Micro
micro -plugin install quoter filemanager

# ZSH
$ROOT/scripts/install-z.sh

# Update user
$ROOT/scripts/chuser.sh

# Set locale
$ROOT/scripts/set_locale.sh
