#! /bin/sh

# Compose key
setxkbmap -option compose:rctrl

# Polybar
~/.config/polybar/launch.sh

# Picom
picom --config ~/.config/picom/picom.conf &

# Wallpaper
feh --bg-center ~/dotfiles/wallpaper.jpg

# Kill sxhkd & start a new instance
pgrep -x sxhkd > /dev/null || sxhkd &

# Define workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	1
bspc config window_gap		6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
