#! /bin/sh

xsetroot -cursor_name left_ptr

# Compose key
setxkbmap -option compose:rctrl

# Polybar
~/.config/polybar/launch.sh

# Picom
picom --config ~/.config/picom/picom.conf --backend xrender &

# Wallpaper
feh --bg-center ~/dotfiles/wallpaper.jpg

# Kill sxhkd & start a new instance
pgrep -x sxhkd > /dev/null || sxhkd &

# Define workspaces
bspc monitor HDMI-A-0 -d I II
bspc monitor DisplayPort-0 -d III IV V VI VII VIII IX X

bspc config border_width	1
bspc config window_gap		6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop=^3
bspc rule -a Spotify desktop=^2
bspc rule -a discord desktop=^1
